### ISSUE TITLE
No iex tab starting

### ISSUE THREAD

**Issue by lehoff** [indiejames/atom-iex#16]
I have tried all versions of opening an iex pane and in all cases there is a window being created, but it disappears almost instantly.

Not an avid Atom user (I only use it for my Junior Beamster class) so I need some pointers on where to dig out information for you.

**Comment by indiejames** [comment]
The tab will close immediately if the IEx session fails to start. You might try running iex in the project directory to make sure it can be started form the shell. Also, iex needs to be in your path. If iex is in your path and you aren't doing this already, try launching atom from the command line using `atom .` in the project directory.

**Comment by lehoff** [comment]
iex is in the path.
It starts from the shell.
Running atom from the project directory does not change anything.

I can see the Erlang/OTP header line and then it dies.

On 13 March 2015 at 16:01, James Norton notifications@github.com wrote:

> The tab will close immediately if the IEx session fails to start. You
> might try running iex in the project directory to make sure it can be
> started form the shell. Also, iex needs to be in your path. If iex is in
> your path and you aren't doing this already, try launching atom from the
> command line using atom . in the project directory.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/indiejames/atom-iex/issues/16#issuecomment-79019614.

## 

http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by indiejames** [comment]
Can you edit ~/.atom/packages/iex/lib/pty.coffee and comment out lines 21 & 22?

```
#emit('iex:exit')
#callback() 
```

This will prevent the window form closing so you can see if there is an error starting up.

**Comment by lehoff** [comment]
I got this error:

Uncaught TypeError: Arguments to path.join must be strings
path.js:472
Hide Stack Trace <#>
TypeError: Arguments to path.join must be strings
at Object.posix.join (path.js:472:13)
at TermView.initialize
(/Users/th/.atom/packages/iex/lib/TermView.coffee:90:39)
at TermView.View
(/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
at new TermView (/Users/th/.atom/packages/iex/lib/TermView.coffee:68:38)
at Object.module.exports.Iex.createTermView
(/Users/th/.atom/packages/iex/lib/iex.coffee:175:18)
at Object.module.exports.Iex.newIEx
(/Users/th/.atom/packages/iex/lib/iex.coffee:265:23)
at atom-workspace.subscriptions.add.atom.commands.add.iex:open
(/Users/th/.atom/packages/iex/lib/iex.coffee:115:26)
at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent
(/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
at
/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent
(/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)

On 14 March 2015 at 20:17, James Norton notifications@github.com wrote:

> Can you edit ~/.atom/packages/iex/lib/pty.js and comment out lines 21 & 22?
> 
> #emit('iex:exit')
> #callback()
> 
> This will prevent the window form closing so you can see if there is an
> error starting up.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/indiejames/atom-iex/issues/16#issuecomment-80682422.

## 

http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by indiejames** [comment]
Apparently I was using a deprecated API to get the project path. I have published a fix. Can you try to install the latest version (0.8.3)?

**Comment by lehoff** [comment]
0.8.3 installed.

New error:
/usr/local/bin/bash: iex: command not found

So this means that your shell is not picking up my .profile, which is okay.

The most platform independent solution seems to be to add a configuration
variable where one can specify the path to iex (and possibly erl) - that
ought to work on all platforms.

On 16 March 2015 at 23:05, James Norton notifications@github.com wrote:

> Apparently I was using a deprecated API to get the project path. I have
> published a fix. Can you try to install the latest version (0.8.3)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/indiejames/atom-iex/issues/16#issuecomment-81962334.

## 

http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by indiejames** [comment]
OK, that makes sense. The shell running iex is not started as a login shell, so It won't pick up your .profile. A lot of people set their paths in .bashrc and source that from .profile or .bash_profile to avoid problems like this. In any case I have changed the code to start up as a login shell so it should work for you now.
You will need to update to the latest version of the package.

**Comment by lehoff** [comment]
It works!

Albeit with this warning:
Warning: could not run smart terminal, falling back to dumb one

But good work!!

On 19 March 2015 at 02:23, James Norton notifications@github.com wrote:

> OK, that makes sense. The shell running iex is not started as a login
> shell, so It won't pick up your .profile. A lot of people set their paths
> in .bashrc and source that from .profile or .bash_profile to avoid problems
> like this. In any case I have changed the code to start up as a login shell
> so it should work for you now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/indiejames/atom-iex/issues/16#issuecomment-83248111.

## 

http://www.linkedin.com/in/torbenhoffmann
@LeHoff
