### ISSUE TITLE
iex term crashing in atom 

### ISSUE THREAD

**Issue by sononix** [indiejames/atom-iex#21]
Project.getPath - /Users/studio/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:583:12
TermView.forkPtyProcess - /Users/studio/.atom/packages/iex/lib/TermView.coffee:57:4
TermView.initialize - /Users/studio/.atom/packages/iex/lib/TermView.coffee:84:19
TermView.View - /Users/studio/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25
new TermView - /Users/studio/.atom/packages/iex/lib/TermView.coffee:53:4
Object.createTermView - /Users/studio/.atom/packages/iex/lib/iex.coffee:120:19

**Comment by indiejames** [comment]
What version is this?

**Comment by sononix** [comment]
I did a reinstall and got it to work finally - tks 
my problem was my pip install was 2.6 and not 2.7 for atom and I installed all dependencies through brew
