### ISSUE TITLE
Start iex session without phoenix.server

### ISSUE THREAD

**Issue by antage** [indiejames/atom-iex#36]
When `atom-iex` detects phoenix application it starts `iex` session with `phoenix.server`. IMHO, it's not very useful due to a long time to start and listen address conflict (I can't start `iex` in Atom editor when I started `mix phoenix.server` in a linux console already).
Could you make `phoenix.server` as optional feature? I really want to start `iex` just as `iex -S mix` without `phoenix.server`.

**Comment by antage** [comment]
@indiejames Thanks!

**Comment by indiejames** [comment]
You're welcome, thanks for the suggestion.
