### ISSUE TITLE
Ability to set elixir and erlang path in settings

### ISSUE THREAD

**Issue by holsee** [indiejames/atom-iex#38]
It would be nice to be able to set the preferred path to elixir and erlang the same way which is present within [autocomplete-elixir package](https://atom.io/packages/autocomplete-elixir) settings:

![screen shot 2016-02-16 at 16 10 51](https://cloud.githubusercontent.com/assets/140169/13082268/e5a458d0-d4c7-11e5-829c-f1be9018c868.png)

It may not always be safe to assume that the user will have the version in the path for both elixir and erlang in which they wish to use in the editor, if these are not set by user it is ok to fall back on the default operation which is currently in place.

**Comment by indiejames** [comment]
I will try to add this tonight. Thanks for the suggestion.
